# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f5a8bc0c2fceded12a9c013836aca01e3df26361243221bf95d9df6fbb621fc54e4cbc02ddb3ac98803dfbf78d3985b129bc545146fe7323d910c59d3a0dd20

test:
  secret_key_base: 33ea75e6c5eb447d7d30fe9381a57bdd392d5b0484c6c9e965929a1ca2a96651303df778a07b97720307bdecf1e3bf1ab0d44c0d2475b94678031f64ee3c2997

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
